# Generated by Django 2.0.4 on 2018-04-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('filesize', models.FloatField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.Directory')),
            ],
        ),
    ]
