# Generated by Django 2.0.4 on 2018-04-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='codename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='files',
            name='filesize',
        ),
    ]
