# Generated by Django 2.0.4 on 2018-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_auto_20180430_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='download_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
