# Generated by Django 2.0.4 on 2018-05-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_files_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filesize',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
